### ISSUE TITLE
Having issues running it on fly.io 

### ISSUE THREAD

**Issue by techsparkling** [addy999/omniparser-api#1]
it would be great if you could help me resolve this problem.

Failed: failed to wait for VM.... in started state: not_found: machine not found

Error: failed to wait for VM.... in started state: not_found: machine not found (Request ID: ....) (Trace ID:....)

When i run fly logs:

2024-11-27T16:53:46Z runner[...] [error]Not enough space to unpack image, possibly exceeds maximum of 8GB uncompressed
Could you please help me fix this issue and also may i know the performance of the model with the current config and the estimated price to run it?

**Comment by techsparkling** [comment]
@addy999 Could you please help me sort this issue out?

**Comment by addy999** [comment]
> @addy999 Could you please help me sort this issue out?

Did you deploy using the provided fly.toml file? Fly has an 8gb disk limit but if you deploy on a GPU machine the limit is quite high. 

Let me know after you double check your config!

**Comment by techsparkling** [comment]
Oh, sorry, my bad! Looks like my fly.toml wasn’t set up right. I’ll fix it and try again. Let you know how it goes!
