### ISSUE TITLE
Will this api be updated to Omniparser 1.5? 

### ISSUE THREAD

**Issue by techsparkling** [addy999/omniparser-api#2]
Hi @addy999 ,

First of all, thank you so much for all this repository. I was wondering if there are any plans to update the API to use Omniparser 1.5. If not, could you please provide instructions on how to update it to the latest version of Omniparser?

**Comment by addy999** [comment]
> Hi @addy999 ,
> 
> First of all, thank you so much for all this repository. I was wondering if there are any plans to update the API to use Omniparser 1.5. If not, could you please provide instructions on how to update it to the latest version of Omniparser?

Thanks for the request - the Dockerfile pulls the `latest` image while building. So all the weights that are downloaded should be from 1.5.

I haven't been able to test the differences in the models, feel free to submit a PR or reply back with some notes. Happy to update where needed.
